export const CONTENT = {
  zh: {
    nav: {
      about:    '關於我',
      projects: '項目',
      skills:   '技術棧',
      contact:  '聯繫方式',
    },
    hero: {
      role:    'Frontend Engineer',
      name:    '我是劉和志，也可以叫我 Henry',
      tagline: 'Live Young Forever，樂觀向上是我的主軸',
      sub:     '擅長使用 React、Tailwind CSS、API 串接\n也是抖音內容創作者，有 11 萬粉絲的創作者背景',
      cta1:    '查看項目',
      cta2:    'GitHub',
    },
    about: {
      label:   '關於我',
      title:   '以真實產品\n為導向的開發',
      body1:   '我有在持續練習以真實產品為導向的前端開發，包含分類系統、購物車、狀態管理與頁面路由，重視組件拆分與代碼可讀性。',
      body2:   '另外我對 AI 工具整合也有一些實作經驗，例如使用 GPT、Claude 協助專案開發。',
      body3:   '精通英文，日文略懂。',
      tiktok:  '抖音創作者 · 11 萬粉絲',
    },
    skills: {
      label: '技術棧',
      title: '使用的工具',
      cats: [
        { name: '前端核心',    items: ['HTML', 'CSS', 'JavaScript (ES6)'] },
        { name: 'React 技術棧', items: ['React', 'React Router', 'Context API', 'Hooks', 'Zustand'] },
        { name: '樣式與 UI',   items: ['Tailwind CSS', 'Component Design', 'Motion', 'RWD'] },
        { name: '工具與流程',  items: ['Git / GitHub', 'Vite', 'REST API', 'Vercel'] },
        { name: 'AI 工具',     items: ['ChatGPT', 'Claude', 'Gemini'] }
],
    },
    projects: {
      label: '項目',
      title: '作品集',
      sub:   '10 個以真實產品為導向的前端專案',
    },
    contact: {
      label: '聯繫方式',
      title: '保持聯繫',
      email: 'henryliu3033@gmail.com',
      github: 'github.com/henryliu3033-afk',
    },
  },
  en: {
    nav: {
      about:    'About',
      projects: 'Projects',
      skills:   'Skills',
      contact:  'Contact',
    },
    hero: {
      role:    'Frontend Engineer',
      name:    "Hi, I'm Henry Liu",
      tagline: 'Live Young Forever — Optimism is my default state',
      sub:     'React · Tailwind CSS · API Integration\nContent creator on TikTok with 110K followers',
      cta1:    'View Projects',
      cta2:    'GitHub',
    },
    about: {
      label:   'About',
      title:   'Product-oriented\nFrontend Development',
      body1:   'I continuously practice product-oriented frontend development, including category systems, shopping carts, state management, and page routing — with a focus on component separation and code readability.',
      body2:   'I also have practical experience integrating AI tools, such as using GPT and Claude to assist in project development.',
      body3:   'Fluent in English, basic Japanese.',
      tiktok:  'TikTok Creator · 110K Followers',
    },
    skills: {
      label: 'Tech Stack',
      title: 'Tools I Use',
      cats: [
        { name: 'Core Frontend',   items: ['HTML', 'CSS', 'JavaScript (ES6)'] },
        { name: 'React Stack',     items: ['React', 'React Router', 'Context API', 'Hooks', 'Zustand'] },
        { name: 'Styling & UI',    items: ['Tailwind CSS', 'Component Design', 'Motion', 'RWD'] },
        { name: 'Tools & Workflow',items: ['Git / GitHub', 'Vite', 'REST API', 'Vercel'] },
        { name: 'AI Tools',        items: ['ChatGPT', 'Claude', 'Gemini'] }
],
    },
    projects: {
      label: 'Projects',
      title: 'Portfolio',
      sub:   '10 product-oriented frontend projects',
    },
    contact: {
      label: 'Contact',
      title: "Let's Connect",
      email: 'henryliu3033@gmail.com',
      github: 'github.com/henryliu3033-afk',
    },
  },
}

export const PROJECTS = [
  {
    id: 1,
    name: 'FORM',
    nameZh: 'FORM — 街頭服飾電商',
    descZh: '高端街頭服飾電商平台，完整購物車、會員系統與訂單管理',
    descEn: 'Premium streetwear e-commerce with full cart, auth & order management',
    tags: ['React', 'Zustand', 'Tailwind'],
    color: '#EF4444',
    github: 'https://github.com/henryliu3033-afk/form',
    demo:   'https://form-indol-pi.vercel.app',
    img:    'https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=600&q=80',
  },
  {
    id: 2,
    name: 'CODA',
    nameZh: 'CODA — 演唱會票務',
    descZh: '極簡黑底演唱會票務平台，事件清單排版、電子票券 QR Code',
    descEn: 'Minimalist concert ticketing platform with list layout & QR e-tickets',
    tags: ['React', 'Zustand', 'Motion'],
    color: '#C8924A',
    github: 'https://github.com/henryliu3033-afk/coda',
    demo:   'https://coda-henna.vercel.app',
    img:    '/images/concert.jpg',
  },
  {
    id: 3,
    name: 'Forge',
    nameZh: 'Forge — AI Prompt Studio',
    descZh: 'AI 提示詞工作室，整合 Claude API，支援模板管理與歷史紀錄',
    descEn: 'AI prompt studio with Claude API integration, template management & history',
    tags: ['React', 'Claude API', 'Tailwind'],
    color: '#58A6FF',
    github: 'https://github.com/henryliu3033-afk/forge',
    demo:   'https://forge-indol-psi.vercel.app',
    img:    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80',
  },
  {
    id: 4,
    name: 'Stockr',
    nameZh: 'Stockr — 股票追蹤',
    descZh: '即時股票追蹤儀表板，接入 Finnhub API，支援自選股與走勢圖',
    descEn: 'Real-time stock tracker with Finnhub API, watchlist & price charts',
    tags: ['React', 'Finnhub API', 'Zustand'],
    color: '#22D47A',
    github: 'https://github.com/henryliu3033-afk/stockr',
    demo:   'https://stockr-theta.vercel.app',
    img:    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
  },
  {
    id: 5,
    name: 'Pure & Co.',
    nameZh: 'Pure & Co. — 手工皂電商',
    descZh: '手工皂品牌電商，台灣配送選項（黑貓、7-11、全家），暖系設計',
    descEn: 'Handmade soap e-commerce with Taiwan CVS pickup & warm earth design',
    tags: ['React', 'Zustand', 'Tailwind'],
    color: '#7A9E7E',
    github: 'https://github.com/henryliu3033-afk/pureandco',
    demo:   'https://pureandco.vercel.app',
    img:    'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80',
  },
  {
    id: 7,
    name: 'SŌRA',
    nameZh: 'SŌRA — 高端餐廳訂位',
    descZh: '現代法式餐廳訂位系統，大字排版美學，三步驟訂位流程',
    descEn: 'Modern French restaurant reservation with editorial typography & 3-step booking',
    tags: ['React', 'Motion', 'Tailwind'],
    color: '#C41E3A',
    github: 'https://github.com/henryliu3033-afk/sora',
    demo:   'https://sora-gray-one.vercel.app',
    img:    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
  },
  {
    id: 8,
    name: 'PULSE',
    nameZh: 'PULSE — 科技媒體',
    descZh: '科技媒體部落格，接入 DEV.to 真實 API，支援搜尋與書籤',
    descEn: 'Tech media blog powered by DEV.to API with live search & bookmarks',
    tags: ['React', 'DEV.to API', 'Zustand'],
    color: '#10B981',
    github: 'https://github.com/henryliu3033-afk/pulse',
    demo:   'https://pulse-omega-three.vercel.app',
    img:    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80',
  },
  {
    id: 9,
    name: 'VitaTrack',
    nameZh: 'VitaTrack — 健康管理',
    descZh: '健康管理 SaaS Dashboard，Sidebar 佈局，SVG 圖表，健康記錄',
    descEn: 'Health management dashboard with sidebar layout, SVG charts & daily logging',
    tags: ['React', 'Zustand', 'SVG Charts'],
    color: '#6366F1',
    github: 'https://github.com/henryliu3033-afk/vitatrack',
    demo:   'https://vitatrack-eta.vercel.app',
    img:    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
  },
  {
    id: 11,
    name: 'REEL',
    nameZh: 'REEL — 影視串流平台',
    descZh: 'Netflix 風格串流平台，接入 TMDB 真實 API，支援搜尋、預告片播放與書籤',
    descEn: 'Netflix-style streaming platform powered by TMDB API with search, trailers & watchlist',
    tags: ['React', 'TMDB API', 'Zustand'],
    color: '#FF6B35',
    github: 'https://github.com/henryliu3033-afk/reel',
    demo:   'https://reel-liard-five.vercel.app',
    img:    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=80',
  },
]
