export const CONTENT = {
  zh: {
    nav: {
      about:    '關於我',
      projects: '項目',
      skills:   '技術棧',
      contact:  '聯繫方式',
    },
    hero: {
      role:    'Full-Stack Engineer',
      name:    '我是劉和志，也可以叫我 Henry',
      tagline: 'Live Young Forever，樂觀向上是我的主軸',
      sub:     '前端 React 打造介面，後端 FastAPI 自建 API、資料庫與快取\n能獨立完成從 UI 到後端、部署的完整產品',
      cta1:    '查看項目',
      cta2:    'GitHub',
    },
    about: {
      label:   '關於我',
      title:   '能獨立交付的\n全端工程師',
      body1:   '我以真實產品為導向開發。前端用 React 打造介面；後端用 FastAPI 自建 RESTful API、JWT 驗證、關聯式與非關聯式資料庫（PostgreSQL / MongoDB）以及 Redis 快取，多個專案前後端皆由我獨立完成並部署上線。',
      body2:   '我習慣用 AI 工具（Claude、GPT）提升開發產能，但堅持理解每一行程式、能獨立除錯並說明設計取捨。',
      body3:   '精通英文，日文略懂。',
      tiktok:  '抖音創作者 · 11 萬粉絲',
    },
    skills: {
      label: '技術棧',
      title: '使用的工具',
      cats: [
        { name: '後端核心',   items: ['Python', 'FastAPI', 'Uvicorn', 'REST API', 'JWT 驗證', 'bcrypt'] },
        { name: '資料庫',     items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'SQLAlchemy'] },
        { name: '前端核心',   items: ['JavaScript (ES6)', 'React', 'React Router', 'Zustand', 'Tailwind CSS'] },
        { name: '部署與工具', items: ['Docker', 'Railway', 'Vercel', 'Git / GitHub', 'Vite'] },
        { name: 'AI 工具',    items: ['ChatGPT', 'Claude', 'Gemini'] }
],
    },
    projects: {
      label: '項目',
      title: '作品集',
      sub:   '10+ 個上線專案，多個前後端全自製（FastAPI + React）',
    },
    contact: {
      label: '聯繫方式',
      title: '保持聯繫',
      email: 'henryliu3033@gmail.com',
      github: 'github.com/henryliu3033-afk',
    },
  },
  en: {
    nav: {
      about:    'About',
      projects: 'Projects',
      skills:   'Skills',
      contact:  'Contact',
    },
    hero: {
      role:    'Full-Stack Engineer',
      name:    "Hi, I'm Henry Liu",
      tagline: 'Live Young Forever — Optimism is my default state',
      sub:     'React on the front, FastAPI + PostgreSQL / MongoDB / Redis on the back\nI build complete products end to end — from UI to API to deployment',
      cta1:    'View Projects',
      cta2:    'GitHub',
    },
    about: {
      label:   'About',
      title:   'A Full-Stack Engineer\nWho Ships End to End',
      body1:   'I build product-oriented apps end to end. On the frontend I use React; on the backend I build RESTful APIs with FastAPI — JWT auth, relational and non-relational databases (PostgreSQL / MongoDB), and Redis caching. Several projects are built and deployed entirely by me, front to back.',
      body2:   'I use AI tools (Claude, GPT) to boost productivity, but I make sure I understand every line, can debug independently, and can explain the trade-offs behind each design.',
      body3:   'Fluent in English, basic Japanese.',
      tiktok:  'TikTok Creator · 110K Followers',
    },
    skills: {
      label: 'Tech Stack',
      title: 'Tools I Use',
      cats: [
        { name: 'Backend',        items: ['Python', 'FastAPI', 'Uvicorn', 'REST API', 'JWT Auth', 'bcrypt'] },
        { name: 'Databases',      items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'SQLAlchemy'] },
        { name: 'Frontend',       items: ['JavaScript (ES6)', 'React', 'React Router', 'Zustand', 'Tailwind CSS'] },
        { name: 'DevOps & Tools', items: ['Docker', 'Railway', 'Vercel', 'Git / GitHub', 'Vite'] },
        { name: 'AI Tools',       items: ['ChatGPT', 'Claude', 'Gemini'] }
],
    },
    projects: {
      label: 'Projects',
      title: 'Portfolio',
      sub:   '10+ deployed projects, several built full-stack (FastAPI + React)',
    },
    contact: {
      label: 'Contact',
      title: "Let's Connect",
      email: 'henryliu3033@gmail.com',
      github: 'github.com/henryliu3033-afk',
    },
  },
}

export const PROJECTS = [
  {
    id: 1,
    name: 'FORM',
    nameZh: 'FORM — 街頭服飾電商',
    descZh: '高端街頭服飾電商平台，完整購物車、會員系統與訂單管理',
    descEn: 'Premium streetwear e-commerce with full cart, auth & order management',
    tags: ['React', 'Zustand', 'Tailwind'],
    color: '#EF4444',
    github: 'https://github.com/henryliu3033-afk/form',
    demo:   'https://form-indol-pi.vercel.app',
    img:    'https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=600&q=80',
    fullstack:     true,
    backendStack:  ['FastAPI', 'MongoDB', 'JWT', 'Docker'],
    backendGithub: 'https://github.com/henryliu3033-afk/form-backend',
  },
  {
    id: 2,
    name: 'CODA',
    nameZh: 'CODA — 演唱會票務',
    descZh: '極簡黑底演唱會票務平台，事件清單排版、電子票券 QR Code',
    descEn: 'Minimalist concert ticketing platform with list layout & QR e-tickets',
    tags: ['React', 'Zustand', 'Motion'],
    color: '#C8924A',
    github: 'https://github.com/henryliu3033-afk/coda',
    demo:   'https://coda-henna.vercel.app',
    img:    '/images/concert.jpg',
    fullstack:     true,
    backendStack:  ['FastAPI', 'MongoDB', 'JWT', 'Docker'],
    backendGithub: 'https://github.com/henryliu3033-afk/coda-backend',
  },
  {
    id: 3,
    name: 'Forge',
    nameZh: 'Forge — AI Prompt Studio',
    descZh: 'AI 提示詞工作室，整合 Claude API，支援模板管理與歷史紀錄',
    descEn: 'AI prompt studio with Claude API integration, template management & history',
    tags: ['React', 'Claude API', 'Tailwind'],
    color: '#58A6FF',
    github: 'https://github.com/henryliu3033-afk/forge',
    demo:   'https://forge-indol-psi.vercel.app',
    img:    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80',
  },
  {
    id: 4,
    name: 'Stockr',
    nameZh: 'Stockr — 股票追蹤',
    descZh: '即時股票追蹤儀表板，接入 Finnhub API，支援自選股與走勢圖',
    descEn: 'Real-time stock tracker with Finnhub API, watchlist & price charts',
    tags: ['React', 'Finnhub API', 'Zustand'],
    color: '#22D47A',
    github: 'https://github.com/henryliu3033-afk/stockr',
    demo:   'https://stockr-theta.vercel.app',
    img:    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
  },
  {
    id: 5,
    name: 'Pure & Co.',
    nameZh: 'Pure & Co. — 手工皂電商',
    descZh: '手工皂品牌電商，台灣配送選項（黑貓、7-11、全家），暖系設計',
    descEn: 'Handmade soap e-commerce with Taiwan CVS pickup & warm earth design',
    tags: ['React', 'Zustand', 'Tailwind'],
    color: '#7A9E7E',
    github: 'https://github.com/henryliu3033-afk/pureandco',
    demo:   'https://pureandco.vercel.app',
    img:    'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80',
  },
  {
    id: 7,
    name: 'SŌRA',
    nameZh: 'SŌRA — 高端餐廳訂位',
    descZh: '現代法式餐廳訂位系統，大字排版美學，三步驟訂位流程',
    descEn: 'Modern French restaurant reservation with editorial typography & 3-step booking',
    tags: ['React', 'Motion', 'Tailwind'],
    color: '#C41E3A',
    github: 'https://github.com/henryliu3033-afk/sora',
    demo:   'https://sora-gray-one.vercel.app',
    img:    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
  },
  {
    id: 8,
    name: 'PULSE',
    nameZh: 'PULSE — 科技媒體',
    descZh: '科技媒體部落格，接入 DEV.to 真實 API，支援搜尋與書籤',
    descEn: 'Tech media blog powered by DEV.to API with live search & bookmarks',
    tags: ['React', 'DEV.to API', 'Zustand'],
    color: '#10B981',
    github: 'https://github.com/henryliu3033-afk/pulse',
    demo:   'https://pulse-omega-three.vercel.app',
    img:    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80',
    fullstack:     true,
    featured:      true,
    backendStack:  ['FastAPI', 'PostgreSQL', 'Redis', 'SQLAlchemy', 'JWT'],
    backendGithub: 'https://github.com/henryliu3033-afk/pulse-backend',
  },
  {
    id: 9,
    name: 'VitaTrack',
    nameZh: 'VitaTrack — 健康管理',
    descZh: '健康管理 SaaS Dashboard，Sidebar 佈局，SVG 圖表，健康記錄',
    descEn: 'Health management dashboard with sidebar layout, SVG charts & daily logging',
    tags: ['React', 'Zustand', 'SVG Charts'],
    color: '#6366F1',
    github: 'https://github.com/henryliu3033-afk/vitatrack',
    demo:   'https://vitatrack-eta.vercel.app',
    img:    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80',
  },
  {
    id: 11,
    name: 'REEL',
    nameZh: 'REEL — 影視串流平台',
    descZh: 'Netflix 風格串流平台，接入 TMDB 真實 API，支援搜尋、預告片播放與書籤',
    descEn: 'Netflix-style streaming platform powered by TMDB API with search, trailers & watchlist',
    tags: ['React', 'TMDB API', 'Zustand'],
    color: '#FF6B35',
    github: 'https://github.com/henryliu3033-afk/reel',
    demo:   'https://reel-liard-five.vercel.app',
    img:    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&q=80',
  },
]
